### ISSUE TITLE
Don't add the .bat suffix when running on windows under Cygwin

### ISSUE THREAD

**Issue by longwa** [ConnorWGarvey/gradle-grails-wrapper#2]
When running under cygwin, the normal grails and gradle (or gradlew) scripts can be used instead of the windows .bat files.

Using the gradle-grails-wrapper, if you run gradlew (instead of gradlew.bat), it converts JAVA_HOME from a windows path to a UNIX style path. When the wrapper runs grails.bat, the JAVA_HOME is invalid.

Seems like when you check for windows using SystemUtils you could just add an additional constraint to check for Cygwin (maybe try running uname -o or perhaps there is a system property) and not add the .bat suffix.

I'd be happy to try to make the change and submit a pull request. BTW, great plugin and I think it will be very handy for us.

**Comment by longwa** [comment]
Actually, after playing around with this more, the bat files on windows work pretty well (I hadn't been using them) and actually fix some of the weird console jline issues that Grails 2.0 has on Cygwin.

**Comment by ConnorWGarvey** [comment]
Glad to hear it worked out :)
